hsv_filter_node:
  ros__parameters:
    #input_topic: "/camera/image_raw" ##SIMULATOR
    input_topic: "static_test/tuning_image" ##REAL
    yellow_mask_topic: "/vision/hsv_mask/yellow"
    yellow_filtered_topic: "/vision/hsv_filtered/yellow"
    blue_mask_topic: "/vision/hsv_mask/blue"
    blue_filtered_topic: "/vision/hsv_filtered/blue"

    # OpenCV HSV ranges: H 0-179, S 0-255, V 0-255
    # Yellow baseline
    yellow_h_min: 36
    yellow_h_max: 67
    yellow_s_min: 78
    yellow_s_max: 174
    yellow_v_min: 104
    yellow_v_max: 158

    # Blue baseline
    blue_h_min: 85
    blue_h_max: 179
    blue_s_min: 152
    blue_s_max: 255
    blue_v_min: 93
    blue_v_max: 255

